package interUser;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.chart.PieChart;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import com.jfoenix.controls.JFXButton;

import ejbService.tettRemote;
import entities.EmplomentOffer;
import entities.Skill;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.scene.control.Label;

public class AAAController {
	@FXML
	private PieChart pie;
	@FXML
	private Button get;
	@FXML
	private JFXButton goo;
	@FXML
	private JFXButton bbbb;
    @FXML
    private Label req;

	// Event Listener on JFXButton[#goo].onAction
	@FXML
	public void goo(ActionEvent event) throws NamingException {
		
		// TODO Autogenerated
		ObservableList<PieChart.Data> list =
                FXCollections.observableArrayList();
		  list.clear();
		Context context = new InitialContext();
		String jndi = "zeusPI-ear/zeusPI-ejb/tett!ejbService.tettRemote";
	tettRemote dao = (tettRemote) context.lookup(jndi);
	Long s=dao.findnb();	
	System.out.println(s+"aaaaaaaaaaaaaaaaaaaaaaaaaaaa");
	req.setText("Number of potential recruitment : "+s);
		
	HashMap<String,Long> a= dao.countskill();
	
	
	
	a.forEach((k,v)->{
		System.out.println(v*100/a.size());
		list.add(  new PieChart.Data(k, (v*100/a.size())));
	});
	
	      //  pie.setTitle("Skills Available in Market ");
          
	        pie.setData(list);
	       
	}
	
	// Event Listener on JFXButton[#bbbb].onAction
	@FXML
	public void bbb(ActionEvent event) {
		// TODO Autogenerated
	}
}
