package interUser;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.sql.Date;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import ejbService.PostServiceEjbRemote;
import entities.User;
import javafx.event.ActionEvent;

import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;

public class userinterfaceController {
	@FXML
	private TextField nomTF;
	@FXML
	private TextField prenomTF;
	@FXML
	private Button ajouterBTN;
	@FXML
	private DatePicker naissancTF;

	// Event Listener on Button[#ajouterBTN].onAction
	@FXML
	public void AjouterAction(ActionEvent event) throws NamingException {
		// TODO Autogenerated
		
		
		
		Context context = new InitialContext();
		String jndi = "zeusPI-ear/zeusPI-ejb/PostServiceEjb!ejbService.PostServiceEjbRemote";
		PostServiceEjbRemote dao = (PostServiceEjbRemote) context.lookup(jndi);
		
		
		User u = new User();
		u.setFirstname(nomTF.getText());
		u.setLastname(prenomTF.getText());
		Date date = Date.valueOf(naissancTF.getValue());
		u.setBirthDate(date);

		System.out.println("   kkkkkkkkkkkkkkkkkkk   "+u);
		u = dao.addUser(u);
		System.out.println("   kkkkkkkkkkkkkkkkkkk   "+u);
	}
	
	
	
}
