package interUser;

import javafx.fxml.FXML;

import javafx.scene.web.WebView;

import javafx.event.ActionEvent;

public class webController {
	@FXML
	private WebView webv;

	// Event Listener on Button.onAction
	@FXML
	public void adress(ActionEvent event) {
		// TODO Autogenerated
		webv.getEngine().load("https://www.google.com/maps/place/ESPRIT/@36.899282,10.1874516,17z/data=!3m1!4b1!4m5!3m4!1s0x12e2cb75abef9f39:0xb7b85ec579f3acb!8m2!3d36.8992777!4d10.1896403");
	}
}
