package UsrInterface;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;

import java.io.File;
import java.io.IOException;
import java.sql.Timestamp;
import java.util.ArrayList;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import ejbService.PostServiceEjbRemote;
import entities.Media;
import entities.Post;
import entities.User;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.stage.FileChooser;
import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class MediaTextController {

	private String imageUrl;

	@FXML
	private Button uploadBtn;
	@FXML
	private ImageView image;
	@FXML
	private Label chemin;
	@FXML
	private TextField descTF;
	@FXML
	private Button addBtn;
	@FXML
	private Button updateBtn;
	@FXML
	private Button displayBtn;
	@FXML
	private Button deleteBtn;
	@FXML
	private TableView<Post> mediaTable;
	@FXML
	private TableColumn<Post, String> urlClmn;
	@FXML
	private TableColumn<Post, String> descrClmn;
	@FXML
	private TableColumn<Post, Timestamp> timeClmn;

	@FXML
	public void upload(ActionEvent event) {
		// TODO Autogenerated

		////// upload image
		FileChooser fileChooser = new FileChooser();
		fileChooser.setTitle("Selectionnez votre image");
		fileChooser.getExtensionFilters()
				.addAll(new FileChooser.ExtensionFilter("Image Files", "*.png", "*.jpg", "*.gif"));
		File selectedFile = fileChooser.showOpenDialog(null);
		if (selectedFile != null) {

			Upload u = new Upload();
			try {
				u.upload(selectedFile);
				imageUrl = u.upload(selectedFile);

			} catch (IOException ex) {
			}

			Image imag = new Image("file:///C://wamp64//www//pi2Images//" + selectedFile.getName());
			chemin.setText("file:///C://wamp64//www//pi2Images//" + selectedFile.getName());
			image.setImage(imag);

		}
	}

	// Event Listener on Button[#addBtn].onAction
	@FXML
	public void addBtnAction(ActionEvent event) throws NamingException {
		// TODO Autogenerated

		Context context = new InitialContext();
		String jndi = "zeusPI-ear/zeusPI-ejb/PostServiceEjb!ejbService.PostServiceEjbRemote";
		PostServiceEjbRemote dao = (PostServiceEjbRemote) context.lookup(jndi);

		User u1 = dao.findUser(3);

		Media m2 = new Media();
		m2.setDescription(descTF.getText());
		m2.setPostTime(new Timestamp(System.currentTimeMillis()));
		m2.setPath_url(imageUrl);
		m2.setUser(u1);

		System.out.println("  userzbi    " + m2 + "      " + imageUrl);
		m2 = (Media) dao.addPost(m2);
		System.out.println("  userzbi    " + m2);

	}

	// Event Listener on Button[#updateBtn].onAction
	@FXML
	public void UpdateAction(ActionEvent event) throws NamingException {
		// TODO Autogenerated
		Post p = (Post) mediaTable.getSelectionModel().getSelectedItem();
		if (p instanceof Media) {

			Media m2 = (Media) p;
			Image imag = new Image(
					"file:///C://wamp64//www//pi2Images//" + m2.getPath_url().replace("localhost:8181//", ""));
			image.setImage(imag);

			
			
			
			
			
			Context context = new InitialContext();
			String jndi = "zeusPI-ear/zeusPI-ejb/PostServiceEjb!ejbService.PostServiceEjbRemote";
			PostServiceEjbRemote dao = (PostServiceEjbRemote) context.lookup(jndi);

			//User u1 = dao.findUser(3);
			
			m2.setDescription(descTF.getText());
			m2.setPostTime(new Timestamp(System.currentTimeMillis()));
			m2.setPath_url(imageUrl);
			//m2.setUser(u1);

			System.out.println("  userzbi    " + m2 + "      " + imageUrl);
			m2 = (Media) dao.updatePost(m2);
			System.out.println("  userzbi    " + m2);
			
		}

	}

	// Event Listener on Button[#displayBtn].onAction
	@FXML
	public void DisplayAction(ActionEvent event) throws NamingException {
		// TODO Autogenerated

		Context context = new InitialContext();
		String jndi = "zeusPI-ear/zeusPI-ejb/PostServiceEjb!ejbService.PostServiceEjbRemote";
		PostServiceEjbRemote dao = (PostServiceEjbRemote) context.lookup(jndi);

		ArrayList<Post> lPosts = dao.findallPosts();
		ObservableList OL = FXCollections.observableArrayList(lPosts);
		mediaTable.setItems(OL);

		urlClmn.setCellValueFactory(new PropertyValueFactory<>("path_url"));
		descrClmn.setCellValueFactory(new PropertyValueFactory<>("description"));
		timeClmn.setCellValueFactory(new PropertyValueFactory<>("postTime"));

	}

	// Event Listener on TableView[#mediaTable].onMouseClicked
	@FXML
	public void MediaSelected(MouseEvent event) {
		// TODO Autogenerated

		Post p = (Post) mediaTable.getSelectionModel().getSelectedItem();
		if (p instanceof Media) {

			Media p1 = (Media) p;
			Image imag = new Image(
					"file:///C://wamp64//www//pi2Images//" + p1.getPath_url().replace("localhost:8181//", ""));
			System.out.println(" hhhhhhhhhhh kkkkkkkkkkkkkk   idpoooooooooossssssst   " + p1.getIdPost());
			image.setImage(imag);

		}
		
		
		
		
	}
	
	@FXML
	public void DeleteAction(ActionEvent event) throws NamingException {
		Post p = (Post) mediaTable.getSelectionModel().getSelectedItem();
		if (p instanceof Media) {

			Media m2 = (Media) p;
			Image imag = new Image(
					"file:///C://wamp64//www//pi2Images//" + m2.getPath_url().replace("localhost:8181//", ""));
			image.setImage(imag);

			
		}
		System.out.println("               type offffffff    "+p.getClass());
		Context context = new InitialContext();
		String jndi = "zeusPI-ear/zeusPI-ejb/PostServiceEjb!ejbService.PostServiceEjbRemote";
		PostServiceEjbRemote dao = (PostServiceEjbRemote) context.lookup(jndi);
		dao.deletePost(p.getIdPost());
		
	}
}
