package templateContact;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.geometry.Pos;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;

import com.jfoenix.controls.JFXTextField;

import ejbService.PostServiceEjbRemote;
import entities.Friend;
import entities.User;
import javafx.event.ActionEvent;

import javafx.scene.control.MenuItem;
import javafx.scene.control.ScrollPane;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import javafx.scene.paint.ImagePattern;
import javafx.scene.Parent;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.Label;
import javafx.scene.control.MenuButton;

import javafx.scene.shape.Circle;
import messageEJB.ChatRoomRemote;

public class contactController implements Initializable {
	@FXML
	private ImageView homeImg;
	@FXML
	private ImageView inboxImg;
	@FXML
	private ImageView jobOfferImg;
	@FXML
	private ImageView notifImg;
	@FXML
	private ImageView contactImg;
	@FXML
	private MenuButton dropDownProfile;
	@FXML
	private MenuItem seeProfileAction;
	@FXML
	private MenuItem jobApplications;
	@FXML
	private MenuItem logOut;
	@FXML
	private Circle profileImg;
	@FXML
	private ImageView statImg;
	@FXML
	private JFXTextField searchTF;


	//////////////////////////////////////////////    vboxxxx
	
	@FXML
	private ScrollPane scrlFrFollow;
	@FXML
	private VBox vbFriendFollow;
	@FXML
	private HBox myNetworkHB;
	@FXML
	private HBox followHB;
	@FXML
	private HBox sendRequestHB;
	@FXML
	private HBox receivedRequestHB;
	@FXML
	private HBox umayKnoHB;
	@FXML
	private HBox entreprisesHB;

	
	
	
	/////////////////////// other parameters

	private User user;
	private Context context;
	String jndi = "zeusPI-ear/zeusPI-ejb/PostServiceEjb!ejbService.PostServiceEjbRemote";
	PostServiceEjbRemote daouser;

	// Event Listener on ImageView[#homeImg].onMouseClicked
	@FXML
	public void homeImgClicked(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("templateHome/home.fxml"));
		homeImg.getScene().setRoot(root);

	}

	// Event Listener on ImageView[#inboxImg].onMouseClicked
	@FXML
	public void inboxImgClicked(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("templateInbox/inbox.fxml"));
		homeImg.getScene().setRoot(root);
	}

	// Event Listener on ImageView[#jobOfferImg].onMouseClicked
	@FXML
	public void jobOfferImgClicked(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("templateJobs/jobs.fxml"));
		homeImg.getScene().setRoot(root);
	}

	// Event Listener on ImageView[#notifImg].onMouseClicked
	@FXML
	public void notifImgClicked(MouseEvent event) throws IOException {
		Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("templateNotif/notif.fxml"));
		homeImg.getScene().setRoot(root);
	}

	// Event Listener on ImageView[#contactImg].onMouseClicked
	@FXML
	public void contactImgAction(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("templateContact/contact.fxml"));
		homeImg.getScene().setRoot(root);
	}

	// Event Listener on MenuItem[#jobApplications].onAction
	@FXML
	public void jobApplicationsAction(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on MenuItem[#logOut].onAction
	@FXML
	public void logOutAction(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Circle[#profileImg].onMouseClicked
	@FXML
	public void profileImgAction(MouseEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on ImageView[#statImg].onMouseClicked
	@FXML
	public void statImgAction(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("templateStat/stat.fxml"));
		homeImg.getScene().setRoot(root);

	}

	//////////////////////////////////////////////////////////////// EJB
	//////////////////////////////////////////////////////////////// services
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub

		try {
			showFriends();
		} catch (NamingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	public void showFriends() throws NamingException {

		context = new InitialContext();
		daouser = (PostServiceEjbRemote) context.lookup(jndi);

		////////////////////////////////////////////////// after Ska
		user = daouser.findUser(3);
		//////////////////////////////////////////////////

		ArrayList<User> lFriends = daouser.findAllFrind(user.getId());

		System.out.println("   bbbbbbbbbbbbbbbbbbbb               " + lFriends.size());

		// vbFriendFollow.setRowIndex(child, value);

		//// vbFriendFollow
		HBox hBox = new HBox();
		hBox.setSpacing(30);
		for (int i = 0; i < lFriends.size(); i++) {

			VBox vb1 = new VBox();

			////////////////////////// lab name
			Label labNameaUser = new Label();
			labNameaUser.setText(lFriends.get(i).getFirstname() + " "
					+ lFriends.get(i).getLastname());
			labNameaUser.setStyle("-fx-font-weight: bold;\n" + "-fx-font: 20 arial;");

			////////////////////////// user picture
			Circle userPicCerc = new Circle(50, 40, 40);
			Image imgUser;
			if (lFriends.get(i).getPictureURL() != null)
				imgUser = new Image(lFriends.get(i).getPictureURL());

			else
				imgUser = new Image("/icons/maleuserBl.png");
			userPicCerc.setFill(new ImagePattern(imgUser));

			////////////////////////// button
			Button btn = new Button("Message");

			btn.setStyle("-fx-background-color: #668cff;");
			vb1.getChildren().addAll(userPicCerc, labNameaUser, btn);
			vb1.setAlignment(Pos.CENTER);
			String cssLayout = "-fx-border-color: #001a1a;";
			vb1.setStyle(cssLayout);
			vb1.setPrefWidth(190);
			vb1.setPrefHeight(209);

			hBox.getChildren().add(vb1);

			if (i % 3 == 2) {
				vbFriendFollow.getChildren().add(hBox);
				hBox = new HBox();
				hBox.setSpacing(30);
			}

			if (i > lFriends.size() - 2)
				vbFriendFollow.getChildren().add(hBox);


		}
		vbFriendFollow.setSpacing(30);

	}
	
	
	
	
	/////////////////////////////////////    pro ctions
	
	@FXML
	public void myNetworkAction(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on HBox[#followHB].onMouseClicked
	@FXML
	public void followingAction(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on HBox[#sendRequestHB].onMouseClicked
	@FXML
	public void sendRequestAction(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on HBox[#receivedRequestHB].onMouseClicked
	@FXML
	public void receivedRequestAction(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on HBox[#umayKnoHB].onMouseClicked
	@FXML
	public void umayKnowAction(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on HBox[#entreprisesHB].onMouseClicked
	@FXML
	public void entrepriseAction(MouseEvent event) {
		// TODO Autogenerated
	}
	

}
