package templateContact;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.geometry.Pos;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JOptionPane;

import com.jfoenix.controls.JFXTextField;

import OtherProfile.otherprofileController;
import ejbService.UserServiceEjbRemote;
import entities.Entreprise;
import entities.Follow;
import entities.Friend;
import entities.Skill;
import entities.User;
import interUser.AcceuilController;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.control.MenuItem;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.Slider;
import javafx.scene.control.TextField;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.layout.VBox;
import javafx.scene.paint.ImagePattern;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.ButtonType;
import javafx.scene.control.ComboBox;
import javafx.scene.control.Label;
import javafx.scene.control.MenuButton;

import javafx.scene.shape.Circle;
import javafx.stage.Stage;


public class contactController implements Initializable {
	@FXML
	private ImageView homeImg;
	@FXML
	private ImageView inboxImg;
	@FXML
	private ImageView jobOfferImg;
	@FXML
	private ImageView notifImg;
	@FXML
	private ImageView contactImg;
	@FXML
	private MenuButton dropDownProfile;
	@FXML
	private MenuItem seeProfileAction;
	@FXML
	private MenuItem jobApplications;
	@FXML
	private MenuItem logOut;
	@FXML
	private Circle profileImg;
	@FXML
	private ImageView statImg;
	@FXML
	private JFXTextField searchTF;


	//////////////////////////////////////////////    vboxxxx
	
	@FXML
	private ScrollPane scrlFrFollow;
	@FXML
	private VBox vbFriendFollow;
	@FXML
	private HBox myNetworkHB;
	@FXML
	private HBox followHB;
	@FXML
	private HBox sendRequestHB;
	@FXML
	private HBox receivedRequestHB;
	@FXML
	private HBox umayKnoHB;
	@FXML
	private HBox entreprisesHB;


	






	
	
	/////////////////////// other parameters


	private User user;
	private Context context;
	  
		String jndi = "zeusPI-ear/zeusPI-ejb/UserServiceEjb!ejbService.UserServiceEjbRemote";
		UserServiceEjbRemote dao ;

	// Event Listener on ImageView[#homeImg].onMouseClicked
	@FXML
	public void homeImgClicked(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("templateHome/home.fxml"));
		homeImg.getScene().setRoot(root);

	}

	// Event Listener on ImageView[#inboxImg].onMouseClicked
	@FXML
	public void inboxImgClicked(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("templateInbox/inbox.fxml"));
		homeImg.getScene().setRoot(root);
	}

	// Event Listener on ImageView[#jobOfferImg].onMouseClicked
	@FXML
	public void jobOfferImgClicked(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("templateJobs/jobs.fxml"));
		homeImg.getScene().setRoot(root);
	}

	// Event Listener on ImageView[#notifImg].onMouseClicked
	@FXML
	public void notifImgClicked(MouseEvent event) throws IOException {
		Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("templateNotif/notif.fxml"));
		homeImg.getScene().setRoot(root);
	}

	// Event Listener on ImageView[#contactImg].onMouseClicked
	@FXML
	public void contactImgAction(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("templateContact/contact.fxml"));
		homeImg.getScene().setRoot(root);
	}

	// Event Listener on MenuItem[#jobApplications].onAction
	@FXML
	public void jobApplicationsAction(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on MenuItem[#logOut].onAction
	@FXML
	public void logOutAction(ActionEvent event) {
		// TODO Autogenerated
	}

	// Event Listener on Circle[#profileImg].onMouseClicked
	@FXML
	public void profileImgAction(MouseEvent event) throws IOException {

		Stage primaryStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
        Parent root = FXMLLoader.load(getClass().getResource("/templateProfile/mypro.fxml"));
        Scene scene = new Scene(root);
        primaryStage.setTitle("My profile!");
        
        primaryStage.setScene(scene);
        primaryStage.show();
	}

	// Event Listener on ImageView[#statImg].onMouseClicked
	@FXML
	public void statImgAction(MouseEvent event) throws IOException {
		// TODO Autogenerated
		Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("templateStat/stat.fxml"));
		homeImg.getScene().setRoot(root);

	}

	//////////////////////////////////////////////////////////////// EJB
	//////////////////////////////////////////////////////////////// services
	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		Image imgUser = new Image(AcceuilController.usconnected.getPictureURL());
		profileImg.setFill(new ImagePattern(imgUser));
		try {
			showFriends();
		} catch (NamingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	public void showFriends() throws NamingException {
		vbFriendFollow.getChildren().removeAll();
		vbFriendFollow.getChildren().clear();
		context = new InitialContext();
		dao = (UserServiceEjbRemote) context.lookup(jndi);

		ArrayList<Friend> lFriends = dao.allmyfriends(AcceuilController.usconnected);
		System.out.println(lFriends.size());
		// vbFriendFollow.setRowIndex(child, value);
	 
		//// vbFriendFollow
		HBox hBox = new HBox();
		hBox.setSpacing(30);
		if (lFriends.size()!=0){
			
			ArrayList<User> lusfriends = new ArrayList();

			
			
		for (int i = 0; i < lFriends.size(); i++)
		{
if(lFriends.get(i).getFriendreciver().getId()==AcceuilController.usconnected.getId()){
	lusfriends.add(lFriends.get(i).getFriendsent());
}else {
	lusfriends.add(lFriends.get(i).getFriendreciver());	
}
		
		}		
		int i=0;
			for (User friend:lusfriends)
		{
	
			
			VBox vb1 = new VBox();

			////////////////////////// lab name
			Label labNameaUser = new Label();
			labNameaUser.setText(friend.getFirstname() + " "
					+ friend.getLastname());
			labNameaUser.setStyle("-fx-font-weight: bold;\n" + "-fx-font: 20 arial;");
	
			////////////////////////// user picture
			Circle userPicCerc = new Circle(50, 40, 40);
			Image imgUser;
			if (friend.getPictureURL() != null)
				imgUser = new Image(friend.getPictureURL());

			else
				imgUser = new Image("/icons/maleuserBl.png");
			userPicCerc.setFill(new ImagePattern(imgUser));

			////////////////////////// action sur image
			userPicCerc.addEventHandler(MouseEvent.MOUSE_CLICKED, new EventHandler<MouseEvent>() {

			     @Override
			     public void handle(MouseEvent event) {
			     
			     
			    	
					try {
					otherprofileController.userviseted=friend;	
						Stage primaryStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
				          Parent root;
						root = FXMLLoader.load(getClass().getResource("/OtherProfile/oprofile.fxml"));
					      Scene scene = new Scene(root);                     
				          primaryStage.setTitle("");
				          primaryStage.setScene(scene);
				          primaryStage.show();
				     		  
				          





					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
			    
			    	 
			    	 
			         event.consume();
			     }
			});
						
		
			//////////////////////////////
			Button btn = new Button("Message");

			btn.setStyle("-fx-background-color: #668cff;");
	
		Image imgrem=new Image("/icons/delete.png");
		ImageView imgremv=new ImageView(imgrem);
		imgremv.addEventHandler(MouseEvent.MOUSE_CLICKED, new EventHandler<MouseEvent>() {

		     @Override
		     public void handle(MouseEvent event) {
		     
		 		try {
					context = new InitialContext();
				
					dao = (UserServiceEjbRemote) context.lookup(jndi);
		 		
					ArrayList<Friend> listf=dao.verifFrinds(friend, AcceuilController.usconnected);
					Friend f=new Friend();
					for(Friend ft:listf)
						f=ft;		
					dao.deleteFriend(f);
					vbFriendFollow.getChildren().removeAll();
					vbFriendFollow.getChildren().clear();
					showFriends();	
		 		} catch (NamingException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				

		    	 
		         event.consume();
		     }
		});
					
		
		
			////////////////////////// lab occupation
			Label occupation = new Label();
			occupation.setText(friend.getActualOccupation() + " At "
					+ friend.getEntreschool());
			occupation.setStyle("-fx-font-weight: bold;\n" + "-fx-font: 15 arial;");
if(!(friend.getActualOccupation()).equals("")){
	vb1.getChildren().addAll(userPicCerc, labNameaUser,occupation, imgremv);}
else{vb1.getChildren().addAll(userPicCerc, labNameaUser, imgremv);};
			
			
			vb1.setAlignment(Pos.CENTER);
			String cssLayout = "-fx-border-color: #001a1a;";
			vb1.setStyle(cssLayout);
			vb1.setPrefWidth(190);
			vb1.setPrefHeight(209);

			hBox.getChildren().add(vb1);

			if (i % 3 == 2) {
				vbFriendFollow.getChildren().add(hBox);
				hBox = new HBox();
				hBox.setSpacing(30);
			}

			if (i > lFriends.size() - 2)
				vbFriendFollow.getChildren().add(hBox);

i++;
		}
		vbFriendFollow.setSpacing(30);

	}
		
	}
	
	public void showFriendsrequest() throws NamingException {
		vbFriendFollow.getChildren().removeAll();
		vbFriendFollow.getChildren().clear();
		context = new InitialContext();
		dao = (UserServiceEjbRemote) context.lookup(jndi);

		ArrayList<Friend> lFriends = dao.allmyfriendsrequests(AcceuilController.usconnected);
System.out.println(lFriends.size());
		// vbFriendFollow.setRowIndex(child, value);
	 
		//// vbFriendFollow
		HBox hBox = new HBox();
		hBox.setSpacing(30);
		if (lFriends.size()!=0){
			
			ArrayList<User> lusfriends = new ArrayList();

			
			
		for (int i = 0; i < lFriends.size(); i++)
		{
if(lFriends.get(i).getFriendreciver().getId()==AcceuilController.usconnected.getId()){
	lusfriends.add(lFriends.get(i).getFriendsent());
}else {
	lusfriends.add(lFriends.get(i).getFriendreciver());	
}
		
		}		
		int i=0;
			for (User friend:lusfriends)
		{
	
			
			VBox vb1 = new VBox();

			////////////////////////// lab name
			Label labNameaUser = new Label();
			labNameaUser.setText(friend.getFirstname() + " "
					+ friend.getLastname());
			labNameaUser.setStyle("-fx-font-weight: bold;\n" + "-fx-font: 20 arial;");
	
			////////////////////////// user picture
			Circle userPicCerc = new Circle(50, 40, 40);
			Image imgUser;
			if (friend.getPictureURL() != null)
				imgUser = new Image(friend.getPictureURL());

			else
				imgUser = new Image("/icons/maleuserBl.png");
			userPicCerc.setFill(new ImagePattern(imgUser));

			////////////////////////// action sur image
			userPicCerc.addEventHandler(MouseEvent.MOUSE_CLICKED, new EventHandler<MouseEvent>() {

			     @Override
			     public void handle(MouseEvent event) {
			     
			     
			    	
					try {
					otherprofileController.userviseted=friend;	
						Stage primaryStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
				          Parent root;
						root = FXMLLoader.load(getClass().getResource("/OtherProfile/oprofile.fxml"));
					      Scene scene = new Scene(root);                     
				          primaryStage.setTitle("");
				          primaryStage.setScene(scene);
				          primaryStage.show();
				     		  
				          





					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
			    
			    	 
			    	 
			         event.consume();
			     }
			});
						
		
			//////////////////////////////
			Button btn = new Button("Message");

			btn.setStyle("-fx-background-color: #668cff;");
	
		Image imgrem=new Image("/icons/delete.png");
		ImageView imgremv=new ImageView(imgrem);
		Image imgaddc=new Image("/icons/addc.png");
		ImageView imgaddcv=new ImageView(imgaddc);
		HBox accrefimg=new HBox();
		accrefimg.setAlignment(Pos.CENTER);
		accrefimg.getChildren().addAll(imgremv,imgaddcv);
		imgremv.addEventHandler(MouseEvent.MOUSE_CLICKED, new EventHandler<MouseEvent>() {

		     @Override
		     public void handle(MouseEvent event) {
		     
		 		try {
					context = new InitialContext();
				
					dao = (UserServiceEjbRemote) context.lookup(jndi);
		 		
					ArrayList<Friend> listf=dao.verifFrinds(friend, AcceuilController.usconnected);
					Friend f=new Friend();
					for(Friend ft:listf)
						f=ft;		
					dao.deleteFriend(f);
					vbFriendFollow.getChildren().removeAll();
					vbFriendFollow.getChildren().clear();
					showFriendsrequest();	
		 		} catch (NamingException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				

		    	 
		         event.consume();
		     }
		});
					
		imgaddcv.addEventHandler(MouseEvent.MOUSE_CLICKED, new EventHandler<MouseEvent>() {

		     @Override
		     public void handle(MouseEvent event) {
		     
		 		try {
		 		 	Friend f=new Friend();
		 	    	context = new InitialContext();
		 			dao = (UserServiceEjbRemote) context.lookup(jndi);
		 			ArrayList<Friend> listf=dao.verifFrinds(friend, AcceuilController.usconnected);
		 			for(Friend ft:listf)
		 				f=ft;
		 		f.setAccepted("friend");
		 		dao.updateFriend(f);
		 		vbFriendFollow.getChildren().removeAll();
				vbFriendFollow.getChildren().clear();	
		 		showFriendsrequest();
					
		 		} catch (NamingException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				

		    	 
		         event.consume();
		     }
		});		
		
			////////////////////////// lab occupation
			Label occupation = new Label();
			occupation.setText(friend.getActualOccupation() + " At "
					+ friend.getEntreschool());
			occupation.setStyle("-fx-font-weight: bold;\n" + "-fx-font: 15 arial;");
if(!(friend.getActualOccupation()).equals("")){
	vb1.getChildren().addAll(userPicCerc, labNameaUser,occupation, accrefimg);}
else{vb1.getChildren().addAll(userPicCerc, labNameaUser, accrefimg);};
			
			
			vb1.setAlignment(Pos.CENTER);
			String cssLayout = "-fx-border-color: #001a1a;";
			vb1.setStyle(cssLayout);
			vb1.setPrefWidth(190);
			vb1.setPrefHeight(209);

			hBox.getChildren().add(vb1);

			if (i % 3 == 2) {
				vbFriendFollow.getChildren().add(hBox);
				hBox = new HBox();
				hBox.setSpacing(30);
			}

			if (i > lFriends.size() - 2)
				vbFriendFollow.getChildren().add(hBox);

i++;
		}
		vbFriendFollow.setSpacing(30);

	}
		
	}
	public void showFriendsrequestssend() throws NamingException {
		vbFriendFollow.getChildren().removeAll();
		vbFriendFollow.getChildren().clear();
		context = new InitialContext();
		dao = (UserServiceEjbRemote) context.lookup(jndi);

		ArrayList<Friend> lFriends = dao.allmyfriendsrequestsent(AcceuilController.usconnected);
		System.out.println(lFriends.size());
		// vbFriendFollow.setRowIndex(child, value);
	 
		//// vbFriendFollow
		HBox hBox = new HBox();
		hBox.setSpacing(30);
		if (lFriends.size()!=0){
			
			ArrayList<User> lusfriends = new ArrayList();

			
			
		for (int i = 0; i < lFriends.size(); i++)
		{
if(lFriends.get(i).getFriendreciver().getId()==AcceuilController.usconnected.getId()){
	lusfriends.add(lFriends.get(i).getFriendsent());
}else {
	lusfriends.add(lFriends.get(i).getFriendreciver());	
}
		
		}		
		int i=0;
			for (User friend:lusfriends)
		{
	
			
			VBox vb1 = new VBox();

			////////////////////////// lab name
			Label labNameaUser = new Label();
			labNameaUser.setText(friend.getFirstname() + " "
					+ friend.getLastname());
			labNameaUser.setStyle("-fx-font-weight: bold;\n" + "-fx-font: 20 arial;");
	
			////////////////////////// user picture
			Circle userPicCerc = new Circle(50, 40, 40);
			Image imgUser;
			if (friend.getPictureURL() != null)
				imgUser = new Image(friend.getPictureURL());

			else
				imgUser = new Image("/icons/maleuserBl.png");
			userPicCerc.setFill(new ImagePattern(imgUser));

			////////////////////////// action sur image
			userPicCerc.addEventHandler(MouseEvent.MOUSE_CLICKED, new EventHandler<MouseEvent>() {

			     @Override
			     public void handle(MouseEvent event) {
			     
			     
			    	
					try {
					otherprofileController.userviseted=friend;	
						Stage primaryStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
				          Parent root;
						root = FXMLLoader.load(getClass().getResource("/OtherProfile/oprofile.fxml"));
					      Scene scene = new Scene(root);                     
				          primaryStage.setTitle("");
				          primaryStage.setScene(scene);
				          primaryStage.show();
				     		  
				          





					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
			    
			    	 
			    	 
			         event.consume();
			     }
			});
						
		
			//////////////////////////////
			Button btn = new Button("Message");

			btn.setStyle("-fx-background-color: #668cff;");
	
		Image imgrem=new Image("/icons/delete.png");
		ImageView imgremv=new ImageView(imgrem);
		imgremv.addEventHandler(MouseEvent.MOUSE_CLICKED, new EventHandler<MouseEvent>() {

		     @Override
		     public void handle(MouseEvent event) {
		     
		 		try {
					context = new InitialContext();
				
					dao = (UserServiceEjbRemote) context.lookup(jndi);
		 		
					ArrayList<Friend> listf=dao.verifFrinds(friend, AcceuilController.usconnected);
					Friend f=new Friend();
					for(Friend ft:listf)
						f=ft;		
					dao.deleteFriend(f);
					vbFriendFollow.getChildren().removeAll();
					vbFriendFollow.getChildren().clear();
					showFriendsrequestssend();	
		 		} catch (NamingException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				

		    	 
		         event.consume();
		     }
		});
					
		
		
			////////////////////////// lab occupation
			Label occupation = new Label();
			occupation.setText(friend.getActualOccupation() + " At "
					+ friend.getEntreschool());
			occupation.setStyle("-fx-font-weight: bold;\n" + "-fx-font: 15 arial;");
if(!(friend.getActualOccupation()).equals("")){
	vb1.getChildren().addAll(userPicCerc, labNameaUser,occupation, imgremv);}
else{vb1.getChildren().addAll(userPicCerc, labNameaUser, imgremv);};
			
			
			vb1.setAlignment(Pos.CENTER);
			String cssLayout = "-fx-border-color: #001a1a;";
			vb1.setStyle(cssLayout);
			vb1.setPrefWidth(190);
			vb1.setPrefHeight(209);

			hBox.getChildren().add(vb1);

			if (i % 3 == 2) {
				vbFriendFollow.getChildren().add(hBox);
				hBox = new HBox();
				hBox.setSpacing(30);
			}

			if (i > lFriends.size() - 2)
				vbFriendFollow.getChildren().add(hBox);

i++;
		}
		vbFriendFollow.setSpacing(30);

	}
		
	}	
////////////////////////////// follow //////////////////////////////////////////
	public void showmyfollow() throws NamingException {
		vbFriendFollow.getChildren().removeAll();
		vbFriendFollow.getChildren().clear();
		context = new InitialContext();
		dao = (UserServiceEjbRemote) context.lookup(jndi);

		ArrayList<Follow> lFriends = dao.allmyfollow(AcceuilController.usconnected);
		System.out.println(lFriends.size());
		// vbFriendFollow.setRowIndex(child, value);
	 
		//// vbFriendFollow
		HBox hBox = new HBox();
		hBox.setSpacing(30);
		if (lFriends.size()!=0){
			
			ArrayList<Entreprise> lusfriends = new ArrayList();

			
			
		for (int i = 0; i < lFriends.size(); i++)
		

	lusfriends.add(lFriends.get(i).getEntreprise());
		
		int i=0;
			for (Entreprise friend:lusfriends)
		{
	
			
			VBox vb1 = new VBox();

			////////////////////////// lab name
			Label labNameaUser = new Label();
			labNameaUser.setText(friend.getName() );
			labNameaUser.setStyle("-fx-font-weight: bold;\n" + "-fx-font: 20 arial;");
	
			////////////////////////// user picture
			Circle userPicCerc = new Circle(50, 40, 40);
			Image imgUser=new Image("icons/entreprise1Bl.png");

			userPicCerc.setFill(new ImagePattern(imgUser));

			////////////////////////// action sur image
			userPicCerc.addEventHandler(MouseEvent.MOUSE_CLICKED, new EventHandler<MouseEvent>() {

			     @Override
			     public void handle(MouseEvent event) {
			     
			     
			    	
					try {
						
						Stage primaryStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
				          Parent root;
						root = FXMLLoader.load(getClass().getResource("/OtherProfile/oprofile.fxml"));
					      Scene scene = new Scene(root);                     
				          primaryStage.setTitle("");
				          primaryStage.setScene(scene);
				          primaryStage.show();
				     		  
				          





					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
			    
			    	 
			    	 
			         event.consume();
			     }
			});
						
		
			//////////////////////////////
			Button btn = new Button("Message");

			btn.setStyle("-fx-background-color: #668cff;");
	
		Image imgrem=new Image("/icons/delete.png");
		ImageView imgremv=new ImageView(imgrem);
		imgremv.addEventHandler(MouseEvent.MOUSE_CLICKED, new EventHandler<MouseEvent>() {

		     @Override
		     public void handle(MouseEvent event) {
		     
		 		try {
					context = new InitialContext();
				
					dao = (UserServiceEjbRemote) context.lookup(jndi);
		 		
					ArrayList<Follow> listf=dao.verifFollow(friend, AcceuilController.usconnected);
					Follow f=new Follow();
					for(Follow ft:listf)
						f=ft;		
					dao.deleteFollow(f);
					vbFriendFollow.getChildren().removeAll();
					vbFriendFollow.getChildren().clear();
					showmyfollow();
		 		} catch (NamingException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				

		    	 
		         event.consume();
		     }
		});
					
		
		
			////////////////////////// lab occupation
		
vb1.getChildren().addAll(userPicCerc, labNameaUser, imgremv);
			
			
			vb1.setAlignment(Pos.CENTER);
			String cssLayout = "-fx-border-color: #001a1a;";
			vb1.setStyle(cssLayout);
			vb1.setPrefWidth(190);
			vb1.setPrefHeight(209);

			hBox.getChildren().add(vb1);

			if (i % 3 == 2) {
				vbFriendFollow.getChildren().add(hBox);
				hBox = new HBox();
				hBox.setSpacing(30);
			}

			if (i > lFriends.size() - 2)
				vbFriendFollow.getChildren().add(hBox);

i++;
		}
		vbFriendFollow.setSpacing(30);

	}
	
	}
	//////////////////////////////////suggestion friend///////////////////////////////////////
	public void showFriendsuggest() throws NamingException {
		vbFriendFollow.getChildren().removeAll();
		vbFriendFollow.getChildren().clear();
		context = new InitialContext();
		dao = (UserServiceEjbRemote) context.lookup(jndi);

		ArrayList<User> lFriends1 = dao.suggestionfriends(AcceuilController.usconnected);
	
		ArrayList<User> lFriends = new ArrayList();
		for (User friend:lFriends1){
			if(dao.verifFrinds(AcceuilController.usconnected, friend).size()==0)
				lFriends.add(friend);
		}
		// vbFriendFollow.setRowIndex(child, value);
	 
		//// vbFriendFollow
		HBox hBox = new HBox();
		hBox.setSpacing(30);

		int i=0;
			for (User friend:lFriends)
		{
	
			
			VBox vb1 = new VBox();

			////////////////////////// lab name
			Label labNameaUser = new Label();
			labNameaUser.setText(friend.getFirstname() + " "
					+ friend.getLastname());
			labNameaUser.setStyle("-fx-font-weight: bold;\n" + "-fx-font: 20 arial;");
	
			////////////////////////// user picture
			Circle userPicCerc = new Circle(50, 40, 40);
			Image imgUser;
			if (friend.getPictureURL() != null)
				imgUser = new Image(friend.getPictureURL());

			else
				imgUser = new Image("/icons/maleuserBl.png");
			userPicCerc.setFill(new ImagePattern(imgUser));

			////////////////////////// action sur image
			userPicCerc.addEventHandler(MouseEvent.MOUSE_CLICKED, new EventHandler<MouseEvent>() {

			     @Override
			     public void handle(MouseEvent event) {
			     
			     
			    	
					try {
					otherprofileController.userviseted=friend;	
						Stage primaryStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
				          Parent root;
						root = FXMLLoader.load(getClass().getResource("/OtherProfile/oprofile.fxml"));
					      Scene scene = new Scene(root);                     
				          primaryStage.setTitle("");
				          primaryStage.setScene(scene);
				          primaryStage.show();
				     		  
				          





					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
			    
			    	 
			    	 
			         event.consume();
			     }
			});
						
		
			//////////////////////////////
			Button btn = new Button("Message");

			btn.setStyle("-fx-background-color: #668cff;");
	
		Image imgrem=new Image("/icons/addc.png");
		ImageView imgremv=new ImageView(imgrem);
		imgremv.addEventHandler(MouseEvent.MOUSE_CLICKED, new EventHandler<MouseEvent>() {

		     @Override
		     public void handle(MouseEvent event) {
		     
		 		try {
					context = new InitialContext();
				
					dao = (UserServiceEjbRemote) context.lookup(jndi);
					Friend nf=new Friend();
					nf.setFriendreciver(friend);
					nf.setFriendsent(AcceuilController.usconnected);
						dao.Addfriend(nf);
					
					vbFriendFollow.getChildren().removeAll();
					vbFriendFollow.getChildren().clear();
					showFriendsuggest();
		 		} catch (NamingException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				

		    	 
		         event.consume();
		     }
		});
					
		
		
			////////////////////////// lab occupation
			Label occupation = new Label();
			occupation.setText(friend.getActualOccupation() + " At "
					+ friend.getEntreschool());
			occupation.setStyle("-fx-font-weight: bold;\n" + "-fx-font: 15 arial;");
if(!(friend.getActualOccupation()).equals("")){
	vb1.getChildren().addAll(userPicCerc, labNameaUser,occupation, imgremv);}
else{vb1.getChildren().addAll(userPicCerc, labNameaUser, imgremv);};
			
			
			vb1.setAlignment(Pos.CENTER);
			String cssLayout = "-fx-border-color: #001a1a;";
			vb1.setStyle(cssLayout);
			vb1.setPrefWidth(190);
			vb1.setPrefHeight(209);

			hBox.getChildren().add(vb1);

			if (i % 3 == 2) {
				vbFriendFollow.getChildren().add(hBox);
				hBox = new HBox();
				hBox.setSpacing(30);
			}

			if (i > lFriends.size() - 2)
				vbFriendFollow.getChildren().add(hBox);

i++;
		}
		vbFriendFollow.setSpacing(30);

	}
	public void showmysuggestentr() throws NamingException {

		vbFriendFollow.getChildren().removeAll();
		vbFriendFollow.getChildren().clear();
		context = new InitialContext();
		dao = (UserServiceEjbRemote) context.lookup(jndi);
		

		ArrayList<Entreprise> lFriends = dao.suggestionentreprise(AcceuilController.usconnected);
System.out.println(lFriends.size());
		// vbFriendFollow.setRowIndex(child, value);
	 
		//// vbFriendFollow
		HBox hBox = new HBox();
		hBox.setSpacing(30);
		if (lFriends.size()!=0){
			
			ArrayList<Entreprise> lusfriends = new ArrayList();

			
			
		for (int i = 0; i < lFriends.size(); i++)
		

	lusfriends.add(lFriends.get(i));
		
		int i=0;
			for (Entreprise friend:lusfriends)
		{
	
			
			VBox vb1 = new VBox();

			////////////////////////// lab name
			Label labNameaUser = new Label();
			labNameaUser.setText(friend.getName() );
			labNameaUser.setStyle("-fx-font-weight: bold;\n" + "-fx-font: 20 arial;");
	
			////////////////////////// user picture
			Circle userPicCerc = new Circle(50, 40, 40);
			Image imgUser=new Image("icons/entreprise1Bl.png");

			userPicCerc.setFill(new ImagePattern(imgUser));

			////////////////////////// action sur image
			userPicCerc.addEventHandler(MouseEvent.MOUSE_CLICKED, new EventHandler<MouseEvent>() {

			     @Override
			     public void handle(MouseEvent event) {
			     
			     
			    	
					try {
						
						Stage primaryStage = (Stage) ((Node) event.getSource()).getScene().getWindow();
				          Parent root;
						root = FXMLLoader.load(getClass().getResource("/OtherProfile/oprofile.fxml"));
					      Scene scene = new Scene(root);                     
				          primaryStage.setTitle("");
				          primaryStage.setScene(scene);
				          primaryStage.show();
				     		  
				          





					} catch (IOException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
			    
			    	 
			    	 
			         event.consume();
			     }
			});
						
		
			//////////////////////////////
			Button btn = new Button("Message");

			btn.setStyle("-fx-background-color: #668cff;");
	
		Image imgrem=new Image("/icons/delete.png");
		ImageView imgremv=new ImageView(imgrem);
		imgremv.addEventHandler(MouseEvent.MOUSE_CLICKED, new EventHandler<MouseEvent>() {

		     @Override
		     public void handle(MouseEvent event) {
		     
		 		try {
					context = new InitialContext();
				
					dao = (UserServiceEjbRemote) context.lookup(jndi);
		 		Follow f=new Follow();
		 		f.setEntreprise(friend);
				f.setUser(AcceuilController.usconnected);
		 		dao.Addfollow(f);
					
			
					vbFriendFollow.getChildren().removeAll();
					vbFriendFollow.getChildren().clear();
					showmysuggestentr();
		 		} catch (NamingException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				

		    	 
		         event.consume();
		     }
		});
					
		
		
			////////////////////////// lab occupation
		
vb1.getChildren().addAll(userPicCerc, labNameaUser, imgremv);
			
			
			vb1.setAlignment(Pos.CENTER);
			String cssLayout = "-fx-border-color: #001a1a;";
			vb1.setStyle(cssLayout);
			vb1.setPrefWidth(190);
			vb1.setPrefHeight(209);

			hBox.getChildren().add(vb1);

			if (i % 3 == 2) {
				vbFriendFollow.getChildren().add(hBox);
				hBox = new HBox();
				hBox.setSpacing(30);
			}

			if (i > lFriends.size() - 2)
				vbFriendFollow.getChildren().add(hBox);

i++;
		}
		vbFriendFollow.setSpacing(30);

	}
	
	}

		
	
	
	/////////////////////////////////////    pro ctions
	
	@FXML
	public void myNetworkAction(MouseEvent event) throws NamingException {
		// TODO Autogenerated
		showFriends();
	}
	// Event Listener on HBox[#followHB].onMouseClicked
	@FXML
	public void followingAction(MouseEvent event) throws NamingException {
		// TODO Autogenerated
		showmyfollow();
	}
	// Event Listener on HBox[#sendRequestHB].onMouseClicked
	@FXML
	public void sendRequestAction(MouseEvent event) throws NamingException {
		// TODO Autogenerated
		showFriendsrequestssend();
	}
	// Event Listener on HBox[#receivedRequestHB].onMouseClicked
	@FXML
	public void receivedRequestAction(MouseEvent event) throws NamingException {
		// TODO Autogenerated
	showFriendsrequest();	
	}
	// Event Listener on HBox[#umayKnoHB].onMouseClicked
	@FXML
	public void umayKnowAction(MouseEvent event) throws NamingException {
		// TODO Autogenerated
		showFriendsuggest();
	}
	// Event Listener on HBox[#entreprisesHB].onMouseClicked
	@FXML
	public void entrepriseAction(MouseEvent event) throws NamingException {
		// TODO Autogenerated
		 showmysuggestentr();
	}
	

}
