package templateContact;

import javafx.fxml.FXML;

import javafx.scene.layout.HBox;

import javafx.event.ActionEvent;

import javafx.scene.control.MenuItem;

import javafx.scene.control.ScrollPane;

import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.MenuButton;

import javafx.scene.shape.Circle;

import javafx.scene.layout.VBox;

public class contact2Controller {
	@FXML
	private ImageView homeImg;
	@FXML
	private ImageView inboxImg;
	@FXML
	private ImageView jobOfferImg;
	@FXML
	private ImageView notifImg;
	@FXML
	private ImageView contactImg;
	@FXML
	private MenuButton dropDownProfile;
	@FXML
	private MenuItem seeProfileAction;
	@FXML
	private MenuItem jobApplications;
	@FXML
	private MenuItem logOut;
	@FXML
	private Circle profileImg;
	@FXML
	private ImageView statImg;
	@FXML
	private ScrollPane scrlFrFollow;
	@FXML
	private VBox vbFriendFollow;
	@FXML
	private HBox myNetworkHB;
	@FXML
	private HBox followHB;
	@FXML
	private HBox sendRequestHB;
	@FXML
	private HBox receivedRequestHB;
	@FXML
	private HBox umayKnoHB;
	@FXML
	private HBox entreprisesHB;

	// Event Listener on ImageView[#homeImg].onMouseClicked
	@FXML
	public void homeImgClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#inboxImg].onMouseClicked
	@FXML
	public void inboxImgClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#jobOfferImg].onMouseClicked
	@FXML
	public void jobOfferImgClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#notifImg].onMouseClicked
	@FXML
	public void notifImgClicked(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#contactImg].onMouseClicked
	@FXML
	public void contactImgAction(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#jobApplications].onAction
	@FXML
	public void jobApplicationsAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem[#logOut].onAction
	@FXML
	public void logOutAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Circle[#profileImg].onMouseClicked
	@FXML
	public void profileImgAction(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView[#statImg].onMouseClicked
	@FXML
	public void statImgAction(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on HBox[#myNetworkHB].onMouseClicked
	@FXML
	public void myNetworkAction(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on HBox[#followHB].onMouseClicked
	@FXML
	public void followingAction(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on HBox[#sendRequestHB].onMouseClicked
	@FXML
	public void sendRequestAction(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on HBox[#receivedRequestHB].onMouseClicked
	@FXML
	public void receivedRequestAction(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on HBox[#umayKnoHB].onMouseClicked
	@FXML
	public void umayKnowAction(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on HBox[#entreprisesHB].onMouseClicked
	@FXML
	public void entrepriseAction(MouseEvent event) {
		// TODO Autogenerated
	}
}
