package displayForum;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.layout.HBox;
import javafx.stage.FileChooser;
import javafx.stage.Stage;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.sql.Timestamp;
import java.util.ResourceBundle;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sound.midi.VoiceStatus;

import UsrInterface.Upload;
import ejbService.PostServiceEjbRemote;
import entities.Media;
import entities.Post;
import entities.User;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.control.TextArea;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;

public class addPostController {
	
	private String imageUrl;
	
	@FXML
	private ImageView image;
	@FXML
	private Label messageLabel;
	@FXML
	private TextArea PostDescText;
	@FXML
	private Label detailsLabel;
	@FXML
	private HBox actionParent;
	@FXML
	private Button uploadBtn;
	@FXML
	private HBox okParent;
	@FXML
	private Button PostBtn;

	
	
	
	
	 
	
	// Event Listener on Button[#uploadBtn].onAction
	@FXML
	public void UploadAction(ActionEvent event) {
		// TODO Autogenerated
		
		FileChooser fileChooser = new FileChooser();
		fileChooser.setTitle("Selectionnez votre image");
		fileChooser.getExtensionFilters()
				.addAll(new FileChooser.ExtensionFilter("Image Files", "*.png", "*.jpg", "*.gif"));
		File selectedFile = fileChooser.showOpenDialog(null);
		if (selectedFile != null) {

			Upload u = new Upload();
			try {
				u.upload(selectedFile);
				imageUrl = u.upload(selectedFile);

			} catch (IOException ex) {
			}

			Image imag = new Image("file:///C://wamp64//www//pi2Images//" + selectedFile.getName());
			//chemin.setText("file:///C://wamp64//www//pi2Images//" + selectedFile.getName());
			image.setImage(imag);

		}
		
		
	}
	// Event Listener on Button[#PostBtn].onAction
	@FXML
	public void PostAction(ActionEvent event) throws NamingException {
		// TODO Autogenerated
		Context context = new InitialContext();
		String jndi = "zeusPI-ear/zeusPI-ejb/PostServiceEjb!ejbService.PostServiceEjbRemote";
		PostServiceEjbRemote dao = (PostServiceEjbRemote) context.lookup(jndi);

		User u1 = dao.findUser(3);

		Media m2 = new Media();
		m2.setDescription(PostDescText.getText());
		m2.setPostTime(new Timestamp(System.currentTimeMillis()));
		m2.setPath_url(imageUrl);
		m2.setUser(u1);

		System.out.println("  userzbi    " + m2 + "      " + imageUrl);
		m2 = (Media) dao.addPost(m2);
		System.out.println("  userzbi    " + m2);
		Stage stage = (Stage) PostBtn.getScene().getWindow();
		stage.close();

		
	}
	
}
